### ISSUE TITLE
lib文件没有上传

### ISSUE THREAD

**Issue by liao10086** [aedoo/ACMSDiscovery#1]
Traceback (most recent call last):
  File "ACMSDiscovery.py", line 10, in <module>
    from lib import function_md5
ImportError: No module named lib

**Comment by Sq-CC** [comment]
这个lib是可以安装的 python -m pip install lib
但是安装完以后，运行程序会说
Traceback (most recent call last):
  File "ACMSDiscovery.py", line 10, in <module>
    from lib import function_md5
ImportError: cannot import name function_md5
